language: cpp

services:
  - docker

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    env:
      - OTB_OS=Linux64
      - OTB_PKG_EXT=run

before_script:
  - docker pull registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv:latest

script:
  - docker run --rm -it --name OTBBV -v $PWD:$PWD -w $PWD registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv:latest /bin/bash -c "cd /opt/otb-bv && git pull;source CI/activate_env_ci.sh;ctest -VV -S ci.cmake -Dci_skip_submit=1"
