language: cpp

git:
  depth: 3

services:
  - docker

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    env:
      - OTB_OS=Linux64
      - OTB_PKG_EXT=run

before_script:
  - mkdir $HOME/build/tromain/otb-bv/data/ImagesTest && mkdir $HOME/build/tromain/otb-bv/data/OutputTest
  - curl -k https://sandbox.zenodo.org/record/721273/files/DATA-BV.tar.gz?download=1 -o $HOME/build/tromain/otb-bv/data/ImagesTest/DATA-BV.tar.gz
  - cd $HOME/build/tromain/otb-bv/data/ImagesTest && tar -xf DATA-BV.tar.gz && cd $HOME/build/tromain/otb-bv
  - docker pull registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv:latest

script:
  - docker run -it -v $PWD:$PWD -w $PWD registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv /bin/bash -c "source CI/activate_env_ci.sh;ctest -VV -S ci.cmake -Dci_skip_submit=1"
