language: cpp

git:
  lfs_skip_smudge: true
  depth: 3

services:
  - docker

jobs:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    sudo: required
    env:
      - OTB_OS=Linux64
      - OTB_PKG_EXT=run

before_script:
  - docker pull registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv:latest

script:
  - docker run -itd --name OTBBV -v $PWD:$PWD -w $PWD registry.orfeo-toolbox.org/orfeotoolbox/otb-build-env/otb-ubuntu-native-develop-bv /bin/bash
  - docker exec OTBBV cd /opt/otb-bv && git pull
  - docker exec OTBBV source CI/activate_env_ci.sh
  - docker exec OTBBV ctest -VV -S ci.cmake -Dci_skip_submit=1
